# Generated by Django 3.2.6 on 2021-08-31 12:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, unique=True, verbose_name='유저 아이디')),
                ('user_pw', models.CharField(max_length=128, verbose_name='유저 비밀번호')),
                ('user_name', models.CharField(max_length=16, verbose_name='유저 이름')),
                ('user_image', models.ImageField(upload_to='studentimages/')),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user_nickname', models.CharField(max_length=16, unique=True, verbose_name='유저 닉네임')),
                ('user_email', models.CharField(max_length=128, unique=True, verbose_name='유저 이메일')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'user',
            },
        ),
    ]
