# Generated by Django 3.2 on 2021-09-04 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeepost',
            name='image',
        ),
        migrations.CreateModel(
            name='committeeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='committeeImage/')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='committee.committeepost')),
            ],
        ),
    ]
