# Generated by Django 3.2.6 on 2021-09-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('committee', '0002_auto_20210905_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeepost',
            name='committee_like',
        ),
        migrations.AlterField(
            model_name='committeecomment',
            name='comment_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
