# Generated by Django 3.2.6 on 2021-09-05 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothcomment',
            name='comment_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AlterField(
            model_name='boothpost',
            name='booth_like',
            field=models.ManyToManyField(blank=True, related_name='booth_like', to='account.Profile'),
        ),
    ]
