# Generated by Django 3.1.3 on 2021-08-30 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='boothTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_tag', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='collegeTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_tag', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='collegePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('college_like', models.ManyToManyField(blank=True, related_name='college_like', to=settings.AUTH_USER_MODEL)),
                ('hashtag_set', models.ManyToManyField(blank=True, to='festival.collegeTags')),
            ],
        ),
        migrations.CreateModel(
            name='boothPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('intro', models.CharField(max_length=30)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('booth_like', models.ManyToManyField(blank=True, related_name='booth_like', to=settings.AUTH_USER_MODEL)),
                ('hashtag_set', models.ManyToManyField(blank=True, to='festival.boothTags')),
            ],
        ),
    ]
