# Generated by Django 3.1.7 on 2021-08-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collegepost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
