# Generated by Django 3.1.7 on 2021-08-30 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collegepost',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='collegeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_contents', models.TextField()),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='festival.collegepost')),
            ],
        ),
        migrations.CreateModel(
            name='boothComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_contents', models.TextField()),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='festival.boothpost')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
