# Generated by Django 3.2.6 on 2021-09-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpost',
            name='college_like',
        ),
        migrations.RemoveField(
            model_name='businesspost',
            name='college_like',
        ),
        migrations.RemoveField(
            model_name='convergencepost',
            name='college_like',
        ),
        migrations.RemoveField(
            model_name='edupost',
            name='college_like',
        ),
        migrations.RemoveField(
            model_name='engineeringpost',
            name='college_like',
        ),
        migrations.RemoveField(
            model_name='hokmapost',
            name='college_like',
        ),
        migrations.RemoveField(
            model_name='humanitiespost',
            name='college_like',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='college_like',
        ),
        migrations.RemoveField(
            model_name='naturalpost',
            name='college_like',
        ),
        migrations.RemoveField(
            model_name='nursingpost',
            name='college_like',
        ),
        migrations.RemoveField(
            model_name='pharmacypost',
            name='college_like',
        ),
        migrations.RemoveField(
            model_name='scratonpost',
            name='college_like',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='college_like',
        ),
    ]
