# Generated by Django 3.2 on 2021-08-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inst',
            name='pub_time',
            field=models.DateTimeField(null=True),
        ),
    ]
