# Generated by Django 3.2.6 on 2021-09-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_auto_20210903_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacypost',
            name='hashtag_set',
        ),
        migrations.DeleteModel(
            name='pharmacyTags',
        ),
    ]
