# Generated by Django 3.2.6 on 2021-09-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_auto_20210905_1536'),
        ('festival', '0003_auto_20210905_0317'),
    ]

    operations = [
    ]
