# Generated by Django 3.2.6 on 2021-09-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_collegepost_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothpost',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
